Repository kowainik/containers-backpack, pull requests merged in 2018-10, with the labels that each got.

#29 [containers-ordered-strict]: reexported functions from containers
  containers-ordered-strict/src/Map/Ord.hs
Labels: Hacktoberfest, instances, refactoring

#30 coerce IntMap
  containers-int-strict/src/Map/Int.hs
Labels: Hacktoberfest, instances

#32 Cleanup `containers-primitive`
  containers-primitive/src/Map/Prim.hs
Labels: Hacktoberfest, instances, refactoring

#36 [containers-int-strict]: Inline and fexpose-all-unfoldings
  containers-int-strict/containers-int-strict.cabal
  containers-int-strict/src/Map/Int.hs
  containers-ordered-strict/containers-ordered-strict.cabal
  containers-ordered-strict/src/Map/Ord.hs
  containers-primitive/containers-primitive.cabal
  containers-primitive/src/Map/Prim.hs
  containers-unordered-strict/containers-unordered-strict.cabal
  containers-unordered-strict/src/Map/Hash.hs
Labels: Hacktoberfest, enhancement, instances

#34 Introduce property tests for various container types
  .travis.yml
  cabal.project
  containers-contrib-readonly/containers-contrib.cabal
  containers-contrib-readonly/src/Map/Contrib/Laws.hs
  containers-contrib/containers-contrib.cabal
  containers-contrib/src/Map/Contrib/Laws.hs
  containers-sig-laws/CHANGELOG.md
  containers-sig-laws/LICENSE
  containers-sig-laws/app/Main.hs
  containers-sig-laws/containers-sig-laws.cabal
Labels: Hacktoberfest, contrib

#43 Introduce Benchmarks
  cabal.project
  containers-contrib-readonly/containers-contrib.cabal
  containers-contrib-readonly/src/Map/Contrib/Bench.hs
  containers-int-strict/containers-int-strict.cabal
  containers-int-strict/src/Map/Int.hs
  containers-primitive/containers-primitive.cabal
  containers-sig-benchmarks/CHANGELOG.md
  containers-sig-benchmarks/LICENSE
  containers-sig-benchmarks/containers-sig-benchmarks.cabal
  containers-sig-benchmarks/src/Main.hs
  containers-sig-readonly/src/Map.hsig
Labels: Hacktoberfest, bench
