Repository kowainik/containers-backpack, pull requests merged in 2018-08, with the labels that each got.

#8 [#1] Add map-unordered for HashMap
  cabal.project
  map-unordered/CHANGELOG.md
  map-unordered/LICENSE
  map-unordered/map-unordered.cabal
  map-unordered/src/Map/HashMap.hs
Labels: enhancement

#14 [#4] Rename packages
  cabal.project
  containers-contrib/CHANGELOG.md
  containers-contrib/LICENSE
  containers-contrib/containers-contrib.cabal
  containers-contrib/src/Map/Contrib/Dummy.hs
  containers-contrib/src/Map/Contrib/Group.hs
  containers-example/LICENSE
  containers-example/app/Main.hs
  containers-example/containers-example.cabal
  containers-int-strict/CHANGELOG.md
  containers-int-strict/LICENSE
  containers-int-strict/containers-int-strict.cabal
  containers-int-strict/src/Map/Int.hs
  containers-ordered-strict/CHANGELOG.md
  containers-ordered-strict/LICENSE
  containers-ordered-strict/containers-ordered-strict.cabal
  containers-ordered-strict/src/Map/Ord.hs
  containers-sig-readonly/CHANGELOG.md
  containers-sig-readonly/LICENSE
  containers-sig-readonly/containers-sig-readonly.cabal
  containers-sig-readonly/src/Map.hsig
  containers-sig/CHANGELOG.md
  containers-sig/LICENSE
  containers-sig/containers-sig.cabal
  containers-sig/src/Map.hsig
  containers-unordered-strict/CHANGELOG.md
  containers-unordered-strict/LICENSE
  containers-unordered-strict/containers-unordered-strict.cabal
  containers-unordered-strict/src/Map/Hash.hs
  map-sig-extended/CHANGELOG.md
Labels: docs, refactoring

#18 Simplify Int type equality
  containers-contrib/containers-contrib.cabal
  containers-contrib/src/Map/Contrib/Dummy.hs
  containers-contrib/src/Map/Contrib/Group.hs
  containers-contrib/src/Map/Contrib/Laws.hs
  containers-int-strict/src/Map/Int.hs
Labels: instances

#19 Add project logo
  README.md
Labels: docs
